---
title: "Normal Muscle vs Highly Infected Tissue Selected Ratios"
author: "<span style='font-size: 17px;'>`r Sys.info()[['user']]`</span><br><span style='font-size: 12px; color:#696969;'>Eberlin Lab, Department of Surgery<br>Baylor College of Medicine</span>"
date: "<span style='font-size: 15px; color: black;'>`r format(Sys.time(), '%B %d, %Y %H:%M')`</span>"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- paste0(Sys.Date(), "_", proj_name);
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })
output: 
  html_document:
    keep_md: yes
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1,h2, h3, h4, h5, p {
text-align: center;
font-size: 20px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = TRUE)
## cache set to TRUE because sometimes otherwise the files directory disappears for some users
```

```{r libraries, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(ggpubr)

library(tidyverse)
library(reshape2)
library(readxl)
library(rawrr)
library(sqldf)
library(readxl)

library(stringr)
library(doParallel)
library(fcluster)
library(johnfuncs)
library(eberlinfuncs)
library(ggh4x)
library(ggrepel)
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\OneDrive - Baylor College of Medicine\Documents\Manoj\Microbial-Project\Data\Match Normal muscle vs Highly Infected)")

## Full path to feature list, otherwise NA
feature_file <- gsub("\\\\", "/", r"(C:\Users\Jacob\OneDrive - Baylor College of Medicine\Documents\Manoj\Microbial-Project\Data\ratio_plot_feature-list.xlsx)")

## Full path to background peak list, otherwise NA
background_file <- NA

## ---------------------------------------------------------------------------

## Scan numbers to import when using raw Thermo files
scans <- 1
#scans <- 50:500 ## number of scans to extract from each raw file

## Mass range to filter
mass_range <- c(100,1000)

## Peak Alignment Method: "clustering", "binning", or "featurelist"
peak_alignment_method <- "clustering"

## If peak alignment method is "clustering":
clust_h <- 0.05 ## Height at which to cut dendrogram to determine clusters

## If peak alignment method is "featurelist":
ppm_error <- 5 ## Mass error tolerance of sample peaks to match to feature peaks

## Normalization Method: "tic", "maxpeak", "median", "medianlog", or "none"
normalization_method <- "tic" 

## Select ratio peaks
## These values come from the gram classification Lasso ratio features
## From "Microbial-Project\outputs\ratio-lasso_gram_featurelist_2025-06-23\2025-06-23_16.12_ratio-lasso_gram_featurelist.html"
ratio_input <- gsub("\\\\", "/", r"(C:\Users\Jacob\OneDrive - Baylor College of Medicine\Documents\Manoj\Microbial-Project\Some expected mz ratio _5aug2025.xlsx)")
ratio_input <- read_xlsx(ratio_input, sheet = "Sheet1") # Ratios picked by Manoj
#ratio_input <- read_xlsx(ratio_input, sheet = "Sheet2") # Ratios selected as gram lasso features

num_mz <- ratio_input$mz1
den_mz <- ratio_input$mz2
```

```{r create output directory, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()))

if(!file.exists(out_dir)) {   
  dir.create(out_dir, recursive = TRUE) 
  }

files_dir <- file.path(out_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files"))

if(!file.exists(files_dir)) {   
  dir.create(files_dir, recursive = TRUE) 
  }
```

```{r other settings}
## Signal-to-Noise Ratio Threshold
SNR_thresh <-  2

## Peak filter
p <- 0.10 ## A peak present in fewer than p*100% of samples is removed, default = 0.10 or 10%

## Randomization seed
seed <- 1234
```

```{r classes}
class_df <- pull_classes(sample_dir)
class_df <- class_df %>%
  mutate(genus = sapply(str_split(V11, " "), `[[`, 1)) %>%
  relocate(genus, .after = V10)
```

``` {r process files}
spec <- process_ms_files(sample_dir, ppm = ppm_error, mass_range = mass_range)

features <- median_binning(spectra_list = spec)
feature_mean_or_median <- "mean"

aligned_spectra <- bin_spectra(
  spectra_list = spec,
  features     = features,
  type         = feature_mean_or_median,
  class_df     = class_df
)

filtered_mz <- switch(
  feature_mean_or_median,
  mean   = features$mean_mz,
  median = features$median_mz
)
```

```{r normalization}
xall <- normalize_pixel(aligned_spectra, normalization_method)
```

``` {r select peaks of interest}
match_with_ppm <- function(target_mz, col_mzs, ppm_tol = 5) {
  ppm_err <- abs(col_mzs - target_mz) / target_mz * 1e6
  hits <- which(ppm_err <= ppm_tol)
  if (length(hits) == 0) {
    NA_integer_
  } else {
    hits[which.min(ppm_err[hits])]
  }
}

col_mzs <- as.numeric(colnames(xall))
num_idx <- sapply(num_mz, match_with_ppm, col_mzs = col_mzs, ppm_tol = ppm_error)
den_idx <- sapply(den_mz, match_with_ppm, col_mzs = col_mzs, ppm_tol = ppm_error)
```

``` {r ratios}
## Build numerator and denominator matrices
numerator <- sapply(num_idx, function(i) if (is.na(i)) rep(0, nrow(xall)) else xall[, i])
denominator <- sapply(den_idx, function(i) if (is.na(i)) rep(0, nrow(xall)) else xall[, i])

## Manually check pairs
head(
  data.frame(
    sample = rownames(xall)[1:5],
    num    = numerator[1:5, 1],
    den    = denominator[1:5, 1],
    ratio  = log(numerator[1:5, 1] / denominator[1:5, 1])
  )
)

## Calculate ratios
ratio_df <- purrr::map_dfr(seq_len(ncol(numerator)), function(i) {
  tibble(
    class = class_df$V10,
    ratio = ifelse(
      numerator[, i] != 0 & denominator[, i] != 0,
      log(numerator[, i] / denominator[, i]),
      NA_real_
    ),
    ratio_label = paste0("m/z ", num_mz[i], " / m/z ", den_mz[i]),
    sample      = rownames(xall),
    species     = class_df$V11
  )
})

## Make sure class is a factor
ratio_df <- ratio_df %>%
  mutate(class = factor(class, levels = sort(unique(class))))

## Split into one df per ratio
ratio_list <- split(ratio_df, ratio_df$ratio_label)
ratio_list <- ratio_list[c(
  "m/z 748.528 / m/z 749.532",
  "m/z 747.518 / m/z 748.528"
)]
```

``` {r plot colors}
species_colors <- c("Staphylococcus aureus" = "#CAB2D6",
                    "Staphylococcus lugdunensis" = "#06B89A",
                    "Staphylococcus epidermidis" = "#6A3D9A",
                    "Enterococcus faecalis" = "#FB9A99",
                    "Enterococcus faecium" = "#841011",
                    "Streptococcus agalactiae"= "#FDBF6F",
                    "Streptococcus anginosus" = "#FF0080",
                    "Streptococcus mitis" = "#00FF00",
                    "Streptococcus pneumoniae" = "#FF7F00",
                    "Streptococcus pyogenes" = "#B15928",
                    "Enterobacter cloacae complex" = "#B2DF8A",
                    "Escherichia coli" = "#33A02C",
                    "Klebsiella pneumoniae" = "#20511D",
                    "Haemophilus influenzae" = "#A6CEE3",
                    "Pseudomonas aeruginosa" = "#1F78B4",
                    "Porphyromonas somerae" = "#760AF8",
                    "Proteus mirabilis" = "#7C6D1D",
                    "Polymicrobial" = "#000000"
                    )
genus_colors <- c("Staphylococcus" = "#9A78B8",
                  "Enterococcus" = "#C05555",
                  "Streptococcus" = "#EB8626",
                  "Enterobacter" = "#B2DF8A",
                  "Escherichia" = "#33A02C",
                  "Klebsiella" = "#20511D",
                  "Haemophilus" = "#A6CEE3",
                  "Pseudomonas" = "#1F78B4")
strep_colors <- c( "#B15928", "#FDBF6F")
staph_strep_colors <- rev(c("#9A78B8", "#EB8626"))
gram_colors <- c("#A2292B", "#6AAC61")
```

``` {r plots}
## Plot each ratio separately and save
## Infinities are capped to just outside the min/max values and labelled accordingly
## Plot each ratio separately and save
library(scales)
library(ggpubr)
library(viridis)
library(ggnewscale)
library(purrr)
library(dplyr)
library(ggplot2)

italicize_species <- function(x) {
  parts <- strsplit(x, " ")[[1]]
  if (length(parts) == 1) return(x)
  genus   <- parts[1]
  species <- parts[2]
  rest    <- parts[-c(1, 2)]
  if (length(rest) == 0) {
    expr_text <- sprintf("italic('%s %s')", genus, species)
  } else {
    rest_text <- paste(rest, collapse = " ")
    expr_text <- sprintf("paste(italic('%s %s'), ' %s')", genus, species, rest_text)
  }
  parse(text = expr_text)[[1]]
}

species_labels_expression <- lapply(names(species_colors), italicize_species)
names(species_labels_expression) <- names(species_colors)

ratio_plots <- imap(ratio_list, function(df, ratio_nm) {
  
  ## Filter out non-finite ratios
  df2 <- df %>%
    filter(is.finite(ratio)) # Removes NA (Including Inf and -Inf from above ratio_df code)

  ## Split by class
  muscle_df  <- df2 %>% filter(class == "Uninfected Muscle")
  species_df <- df2 %>% filter(class != "Uninfected Muscle")

  ## Define colors
  muscle_names <- sort(unique(muscle_df$species))
  species_names <- sort(unique(species_df$species))

  muscle_cols  <- c("red", "blue")[seq_along(muscle_names)]
  # species_cols <- viridisLite::viridis(length(species_names), option = "H")

  ## Define y-axis breaks
  fin <- df2$ratio
  fin_breaks <- pretty(fin, 5)

  ## Base plot
  p <- ggplot(df2, aes(x = class, y = ratio)) +
    
    ## Neutral boxplots
    geom_boxplot(
      width = 0.4, outlier.shape = NA, alpha = 0.2,
      color = "black", fill = "gray90"
    ) +

    ## Muscle points
    geom_jitter(
      data = muscle_df,
      aes(fill = species),
      color = "black",
      shape = 21,               # filled circles
      width = 0.15, size = 2.8, alpha = 0.75,
      show.legend = TRUE,
      stroke = 0
    ) +
    scale_fill_manual(
      name = "Uninfected Muscle Type",
      values = setNames(muscle_cols, muscle_names),
      guide = guide_legend(
        override.aes = list(
          shape = 21,
          size = 3,
          fill = muscle_cols,
          alpha = 0.75,   ## <-- MATCH ALPHA HERE
          stroke = 0
        ),
        order = 2
      )
    ) +

    ## Reset color scale for species legend
    ggnewscale::new_scale_color() +

    ## Species points
    geom_jitter(
      data = species_df,
      aes(color = species),
      shape = 16,               # same as muscle points visually
      width = 0.15, size = 2.3, alpha = 0.75,
      show.legend = TRUE
    ) +
    scale_color_manual(
      name = "Highly Infected Species",
      values = species_colors,
      labels = species_labels_expression,
      guide = guide_legend(
        override.aes = list(size = 3, alpha = 0.75),
        order = 1
      )
    ) +

    ## Wilcoxon Test
    {
      if (n_distinct(df2$class) == 2) {
        stat_compare_means(
          data = df2,
          method = "wilcox.test",
          comparisons = list(c("Uninfected Muscle", "Highly Infected Tissue")),
          label = "p.format",
          label.x = 1.5,
          label.y = max(df2$ratio, na.rm = TRUE) * 1.02,
          size = 5
        )
      } else NULL
    } +

    ## Axis & Theme
    scale_y_continuous(
      breaks = fin_breaks,
      expand = expansion(mult = c(0.05, 0.1))
    ) +
    labs(
      title = NULL,
      x = "Tissue Type",
      y = "log(Intensity Ratio)"
    ) +
    theme_minimal(base_size = 14) +
    theme(
      axis.text.x   = element_text(size = 11),
      plot.title.position = "plot",
      plot.title    = element_text(hjust = 0.5, margin = margin(b = 10)),
      plot.margin = margin(t = 20, r = 20, b = 20, l = 20),
      legend.position = "right",
      legend.box = "vertical"
    )

  ## Save
  safe_nm <- paste0("ratio_", gsub("[^0-9A-Za-z]+", "_", ratio_nm), ".png")
  ggsave(
    filename = file.path(files_dir, safe_nm),
    plot     = p,
    width    = 9, height = 12,
    dpi      = 300, bg = "white"
  )

  return(p)
})
```

``` {r combined figure}
title_A <- bquote(bold("A. Ratios of " * bolditalic("m/z") * " 747.518 : " * bolditalic("m/z") * " 748.528"))
title_B <- bquote(bold("B. Ratios of " * bolditalic("m/z") * " 748.528 : " * bolditalic("m/z") * " 749.532"))

p1 <- ratio_plots[["m/z 747.518 / m/z 748.528"]] + ggtitle(title_A) +
  theme(plot.title = element_text(hjust = 0))

p2 <- ratio_plots[["m/z 748.528 / m/z 749.532"]] + ggtitle(title_B) +
  theme(plot.title = element_text(hjust = 0))

combined_plot <- ggarrange(
  p1, p2,
  ncol = 2, nrow = 1,
  common.legend = TRUE,
  legend = "right",
  align = "hv"
)
```

``` {r panel c}
## Normalize and pivot for spectra panel
xall1 <- normalize_pixel(aligned_spectra, "maxpeak")

xall_zoom <- normalize_pixel(
  aligned_spectra[, which(
    as.numeric(colnames(aligned_spectra)) >= 747 &
      as.numeric(colnames(aligned_spectra)) <= 750)],
  "maxpeak"
)

d <- xall %>%
  rownames_to_column("sample_name") %>%
  pivot_longer(!sample_name, names_to = "mz", values_to = "intensity") %>%
  mutate(mz = as.numeric(mz))

d1 <- xall1 %>%
  rownames_to_column("sample_name") %>%
  pivot_longer(!sample_name, names_to = "mz", values_to = "intensity") %>%
  mutate(mz = as.numeric(mz))

d_zoom <- xall_zoom %>%
  rownames_to_column("sample_name") %>%
  pivot_longer(!sample_name, names_to = "mz", values_to = "intensity") %>%
  mutate(mz = as.numeric(mz))

## Select the two samples
isolate_specimen_match <- d %>%
  filter(str_detect(sample_name,
                    regex("1046|November-27-2024-SD-24-263-smoothmuscle",
                          ignore_case = TRUE))) %>%
  mutate(
    patient_id = case_when(
      str_detect(sample_name, "1046") ~ "1046",
      str_detect(sample_name, "November-27-2024-SD-24-263-smoothmuscle") ~ "SD-24-263",
      TRUE ~ "oops"
    ),
    sample_type = ifelse(str_detect(sample_name, "1046"),
                         "Infected Tissue", "Uninfected Muscle"),
    zoom = "Full Spectrum"
  )

isolate_specimen_match1 <- d1 %>%
  filter(str_detect(sample_name,
                    regex("1046|November-27-2024-SD-24-263-smoothmuscle",
                          ignore_case = TRUE))) %>%
  mutate(
    patient_id = case_when(
      str_detect(sample_name, "1046") ~ "1046",
      str_detect(sample_name, "November-27-2024-SD-24-263-smoothmuscle") ~ "SD-24-263",
      TRUE ~ "oops"
    ),
    sample_type = ifelse(str_detect(sample_name, "1046"),
                         "Infected Tissue", "Uninfected Muscle"),
    zoom = "Full Spectrum"
  )

isolate_specimen_match_zoom <- d_zoom %>%
  filter(str_detect(sample_name,
                    regex("1046|November-27-2024-SD-24-263-smoothmuscle",
                          ignore_case = TRUE))) %>%
  mutate(
    patient_id = case_when(
      str_detect(sample_name, "1046") ~ "1046",
      str_detect(sample_name, "November-27-2024-SD-24-263-smoothmuscle") ~ "SD-24-263",
      TRUE ~ "oops"
    ),
    sample_type = ifelse(str_detect(sample_name, "1046"),
                         "Infected Tissue", "Uninfected Muscle"),
    zoom = "Ratio Peaks Region"
  )

dd  <- rbind(isolate_specimen_match,  isolate_specimen_match_zoom)
dd1 <- rbind(isolate_specimen_match1, isolate_specimen_match_zoom)

## Ratio-defining peaks and names
mol <- tibble(
  mz    = c(747.518, 748.528, 749.531),
  annot = c("PG 34:1", "PE O-38:6", "PG 34:0")
)

isolate_specimen_match1 <- merge(isolate_specimen_match1, mol,
                                 by = "mz", all.x = TRUE)
dd1 <- merge(dd1, mol, by = "mz", all.x = TRUE)

## Build labeling columns
dd1 <- dd1 %>%
  mutate(
    facet_col = paste0(patient_id, " - ", sample_type),
    facet_col = factor(facet_col,
                       levels = c("1046 - Infected Tissue",
                                  "SD-24-263 - Uninfected Muscle")),
    annot2 = ifelse(!is.na(annot),
                    paste0("bold('", annot, "')"),
                    NA_character_),
    annot3 = paste0("'", format(round(mz, 3), nsmall = 3), "'")
  )

## Top 5 peaks (by intensity) in zoom region, per sample
top_mz_peaks <- dd1 %>%
  filter(zoom == "Ratio Peaks Region") %>%
  group_by(facet_col) %>%
  slice_max(intensity, n = 3, with_ties = FALSE) %>%
  ungroup()
```

``` {r panel_3}
## Build panel c
p3 <- ggplot(dd1, aes(x = as.numeric(mz), y = intensity * 100)) + 
  ## Sample labels (placed once per row) 
  geom_text( 
    data = distinct(dd1, facet_col), 
    aes(x = 300, y = 95, label = facet_col), 
    hjust = 0, 
    size = 5, 
    fontface = "bold" 
    ) + 
  
  coord_cartesian(clip = "off") + 
  ## Labels & theme 
  labs( 
    title = NULL, 
    x = "", 
    y = "Relative Intensity (%)" 
  ) + 
  
  ## Vertical callout lines 
  geom_vline( 
    data = mol %>% mutate(zoom = "Full Spectrum"), 
    aes(xintercept = mz), 
    color = "#cab2d6", 
    linewidth = 1, 
    alpha = 0.6, 
  ) + 
  
  ## Mass spectrum 
  geom_bar(stat = "identity", width = 0.001, color = "#1d1d1d") +
  
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid = element_blank(), 
        panel.spacing.y = unit(1, "lines"), 
        strip.background = element_blank(), 
        strip.text = element_blank(), 
        axis.line.x = element_line(linewidth = 0.2, colour = "black"), 
        axis.line.y = element_line(linewidth = 0.2, colour = "black"), 
        axis.ticks = element_line(linewidth = 0.2, colour = "black"), 
        plot.background = element_rect(fill = "white"), 
        text = element_text(size = 14), 
        legend.position = "none", 
        plot.margin = margin(20, 20, 30, 20)) + 
  
  ## Facet layout 
  ggh4x::facet_grid2( 
    facet_col ~ zoom, 
    scales = "free", 
    independent = "all" 
  ) + 
  
  ## Independent zoom scaling 
  facetted_pos_scales( 
    x = list( 
      zoom == "Full Spectrum" ~ scale_x_continuous( 
        breaks = seq(100, 1000, by = 100), 
        expand = expansion(mult = c(0, 0), add = c(5, 5)) 
      ), 
      zoom == "Ratio Peaks Region" ~ scale_x_continuous( 
        limits = c(747, 750), 
        breaks = seq(747, 750, by = 0.5), 
        expand = expansion(mult = c(0, 0), add = c(0.25, 0.25)) 
      ) 
    ), 
    y = list(
      zoom == "Full Spectrum" ~ scale_y_continuous(
        limits = c(0, 100),
        breaks = seq(0, 100, 10),
        expand = c(0, 0)
      ),
      zoom == "Ratio Peaks Region" ~ scale_y_continuous(
        limits = c(0, 100),
        breaks = seq(0, 100, 20),
        expand = c(0, 0)
      )
    )
  ) + 
  
  ## Panel width ratio (full wider than zoom) 
  force_panelsizes(cols = c(4, 2)) + 
  
  geom_text_repel(data = top_mz_peaks, 
                  aes(x = as.numeric(mz), y = intensity * 100, label = annot3),
                  direction = "y", 
                  vjust = -0.6, 
                  hjust = 0.5, 
                  force = 1, 
                  min.segment.length = 0, 
                  na.rm = TRUE, 
                  size = 4, 
                  color = "black", 
                  parse = TRUE, 
                  segment.color = NA) + 

  geom_text(data = data.frame(zoom = "Full Spectrum"), 
            x = c(NA, 500), 
            y = -15, 
            label = "m/z", 
            hjust = 0.5, 
            size = 5, 
            fontface = "bold.italic") + 
  geom_text(data = data.frame(zoom = "Ratio Peaks Region"), 
            x = c(NA, 748.5), 
            y = -15, 
            label = "m/z", 
            hjust = 0.5, 
            size = 5, 
            fontface = "bold.italic")

p3
```

``` {r save figure 4}
## Add panel-C title
title_C <- bquote(bold("C. Mass spectra of infected tissue and uninfected muscle and their ratio-defining peaks"))
p3 <- p3 + ggtitle(title_C) +
  theme(plot.title = element_text(hjust = 0, size = 16, face = "bold"))


#### ---- Combine into Figure 4 ---- ####
combined_plot2 <- ggarrange(
  combined_plot,
  p3,
  ncol   = 1,
  nrow   = 2,
  align  = "hv"
)

ggsave(
  filename = file.path(files_dir, "fig4-combined_ratio_panels.png"),
  plot     = combined_plot2,
  width    = 14,
  height   = 16,
  dpi      = 300,
  bg       = "white",
  units    = "in"
)
```

<br>

#### **Preprocessing and Statistical Model Settings**

```{r chunk3, fig.align = "center"}
if (peak_alignment_method == "clustering") {
  cluster_bin_size <- c("Cluster Height:", clust_h)
} else if (peak_alignment_method == "binning") {
  cluster_bin_size <- c("Bin Size:", "0.01")
} else if (peak_alignment_method == "featurelist") {
  cluster_bin_size <- c("Peak Mass Error:", paste0(ppm_error, " ppm"))
}

if (is.null(background_file)) {
  bg_exclusion <- "no"
} else if (!is.null(background_file)) {
  bg_exclusion <- "yes"
}

settings_df <- rbind(#c("SNR Threshold:", SNR_thresh),
                     c("Mass Range:", paste0('<i>m/z</i> ', mass_range[1], " - ", mass_range[2])),
                     c("Peak Alignment Method:", peak_alignment_method),
                     cluster_bin_size,
                     c("Background Peak Exclusion:", bg_exclusion),
                     c("Normalization Method:", normalization_method))

kable(settings_df,
      row.names = FALSE,
      align = "l",
      format = "html",
      escape = FALSE)%>%
  column_spec(1:2, width = "3in")%>% 
  kable_styling(full_width = FALSE, 
                font_size = 14)
```

```{r R data, include = FALSE}
#save(list = ls(), 
#     file=file.path(files_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", #proj_name,"_preproc.RData")))
```

<br>

#### **Session Info**

```{r}
sessionInfo()
```