---
title: "Ratio Lasso - Gram Stain Prediction"
subtitle: "Renamed Sample Files"
author: 
  - "Code author: Jacob Mardick"
  - "Code run by: `r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()));
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })

output: 
  html_document:
    keep_md: yes
    df_print: paged
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1, h2, h3, h4, h5 {
font-size: 20px;
}

h1, h2, h3, h4, h5, p {
text-align: center;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE)
```

```{r libraries, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(ggpubr)

library(tidyverse)
library(reshape2)
library(readxl)
library(rawrr)
library(sqldf)

library(stringr)
library(doParallel)
library(fcluster)
library(johnfuncs)

library(caret) ## automates supervised learning (predictive modeling)
library(glmnet) ## for training, cross validation, and testing model
library(pROC) ## for plotting ROC curve
library(scales) ## for integer y-axis on histogram
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
## PASTE PATH IN BETWEEN INNER PARENTHASIS WITH QUOTES ON THE OUTSIDE -- NO NEED TO CHANGE BACKSLASHES TO FORWARD SLASHES
sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\People\MANOJ\Renamed_Gram_positive_Gram_negative_Isolates_May2025\Excel files)")

## Full path to feature list, otherwise NULL
feature_file <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\People\MANOJ\Renamed_Gram_positive_Gram_negative_Isolates_May2025\Microbial Manuscript Oct_2025\PNAS_Microbes_Supplementary_MSMS_30OCT2025.xlsx)")

## Full path to background peak list, otherwise NULL
background_file <- NULL

## ---------------------------------------------------------------------------

## Mass range to filter
mass_range <- c(100,1000)

## Peak Alignment Method: "clustering" or "featurelist"
peak_alignment_method <- "featurelist"

## If peak alignment method is "clustering":
clust_h <- 0.05 ## Height at which to cut dendrogram to determine clusters
clust_int_method  <-  "sumints" ## Handling of multiple intensities aggregating to one cluster centroid: "sumints" or "maxint"

## If peak alignment method is "featurelist":
ppm_error <- 5 ## Mass error tolerance of sample peaks to match to feature peaks

## Normalization Method: "tic", "maxpeak", "median", "medianlog", or "none"
normalization_method <- "tic" 

## ---------------------------------------------------------------------------

## Fraction of samples to use for training lasso model
train_fraction <- 0.7

## Randomization seed
seed <- 1234
```

```{r create directory for output files, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()))

if(!file.exists(out_dir)) {   
  dir.create(out_dir, recursive = TRUE) 
  }

files_dir <- file.path(out_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files"))

if(!file.exists(files_dir)) {   
  dir.create(files_dir, recursive = TRUE) 
  }
```

```{r file extension}
## 
classes_path <- gsub(file.path(sample_dir, "/"), "", list.dirs(sample_dir)[c(-1)], fixed=TRUE)

classes <- strsplit(classes_path, "/")
classes <- classes[lapply(classes,length)==1]

classes_path <- lapply(classes, function(x) paste(x, collapse = '/'))

classes <- sapply(classes, `[`, 1)
classes <- unique(classes)
classes <- classes[!is.na(classes)]
classes <- trimws(classes)

names(classes_path) <- classes

## check file extension
sample_file_ext <- "xlsx"
```

```{r file and sample names}
## file names
file_name_list <- lapply(classes_path, function(x) 
  list.files(path = file.path(sample_dir,x), pattern = paste0("*.", sample_file_ext), full.names = TRUE, recursive = TRUE))

## Ensure patient ordering is consistent across different OSes.
file_name_list <- lapply(file_name_list, sort)

## sample names
sample_names_list <- lapply(file_name_list, function(x) tools::file_path_sans_ext(basename(x)))
names(sample_names_list) <- classes
sample_names <- unlist(sample_names_list)
sample_names_df <- purrr::map_df(sample_names_list, ~as.data.frame(.x), .id="id")
colnames(sample_names_df) <- c("class", "sample_name")
```

```{r}
## fixed objects for exporting to parallel computing
fixed_objects <- list(mass_range = mass_range)
```

```{r excel data}
if (sample_file_ext == "xlsx") {
  
  process_xlsx <- function(file_name_list, fixed_objects) {
    cl <- makeCluster(detectCores() - 1) # Use one less than the number of available cores
    registerDoParallel(cl)
    
    # clusterEvalQ(cl, {
    #   library(dplyr)
    #   library(readxl)
    #   library(purrr)
    # })
    
    #clusterExport(cl, list("mass_range"))
    
    result <- foreach(i = seq_along(file_name_list), .packages = c('dplyr', 'readxl', 'purrr')) %:% 
      foreach(j = seq_along(file_name_list[[i]])) %dopar% {
        
        ## extract m/z and intensity into list of lists
        spectrum <- tryCatch(read_excel(file_name_list[[i]][[j]], 
                                        col_names = c("mass", "intensity"), 
                                        skip = 8), 
                             error = function(e) tryCatch(read_excel(file_name_list[[i]][[j]], 
                                                                     col_names = c("mass", "intensity", "relative"), 
                                                                     skip = 8),
                                                          error = function(e) return(read_excel(file_name_list[[i]][[j]], 
                                                                                                col_names = c("mass", "intensity", "relative", "noise"), 
                                                                                                skip = 8))))
        
        ## FILTER #1: RETAIN PEAKS WITHIN MASS RANGE
        spectrum <- spectrum[spectrum$mass >= fixed_objects$mass_range[1] & spectrum$mass <= fixed_objects$mass_range[2], ]
        
        ## FILTER #2: RETAIN PEAKS WITH SNR >= 2
        spectra_list <- if(length(spectrum) == 4) {
          ## Add SNR column
          spectrum$SNR <- (spectrum$intensity)/(spectrum$noise)
          
          spectrum <- tryCatch(subset(spectrum, SNR >= 2),
                               error = function(e) return(spectrum))
          
          ## Remove columns "relative", "noise", and "SNR"
          spectrum <- subset(spectrum, select = -c(relative, noise, SNR))
          
          return(spectrum)
        }else if(length(spectrum) == 3){
          ## Remove column "relative"
          spectrum <- spectrum[, !colnames(spectrum) %in% c("relative")]
          
          return(spectrum)
        }else if(length(spectrum) == 2){
          return(spectrum)
        }
      }
    
    stopCluster(cl)
    return(result)
  }
  
  spectra_list <- process_xlsx(file_name_list, fixed_objects)
  
  ## Set sample names and classes of spectra_list
  spectra_list <- lapply(seq_along(spectra_list), \(i) setNames(spectra_list[[i]], sample_names_list[[i]]))
  names(spectra_list) <- classes
}
```

```{r peak alignment clustering}
## If peak alignment method is clustering
if (peak_alignment_method == "clustering") {
  
  ## If background peak list: add background peaks to clustering
  if (!is.null(background_file)) {
    bg_mz <- unlist(read.csv(background_file, header = FALSE))
    
    sample_mz <- sort(unlist(
      lapply(spectra_list, function(y)
        lapply(y, function(x)
          round(x$mass, 3)))))
    
    all_mz <- c(bg_mz, sample_mz)
    names(all_mz) <- all_mz
    
  } else { ## If no background peak list
    all_mz <- sort(unlist(
      lapply(spectra_list, function(y)
        lapply(y, function(x)
          round(x$mass, 3)))))
    
    names(all_mz) <- all_mz
  }
  
  ## Cluster peaks into centroids
  tree <- fcluster(all_mz)
  clust_mz <- fcutree(all_mz, tree, h=clust_h)
  clustMZ <- sort(clust_mz$cen)
  
  ## Match cluster centroids to sample peaks
  clusterMatrixList <- lapply(spectra_list, function(x, y, z, w) 
    get_cluster_matrix(x, y, z, w), y=clustMZ, z = clust_h, w = clust_int_method)
  
  preprocList <- lapply(clusterMatrixList, function(x) as.matrix(get_data_matrix_clustering(x)))
  
  save(preprocList, 
       file = file.path(files_dir, 
                        paste0(peak_alignment_method,
                               "_h", clust_h, clust_int_method,
                               "_preprocList.RData")))
  
  aligned_spectra <- do.call(rbind, preprocList)
  
  colnames(aligned_spectra) <- clustMZ
  rownames(aligned_spectra) <- sample_names
  
  ## FILTER #3: REMOVE RARE/UNCOMMON PEAKS PRESENT < 10% SAMPLES
  mz_count_filter <- colSums(aligned_spectra != 0) > as.integer(nrow(aligned_spectra)*0.10)
  aligned_spectra <- aligned_spectra[, mz_count_filter]
  
  ## FILTER #4: REMOVE BACKGROUND PEAKS (IF BACKGROUND FILE PRESENT)
  if (!is.null(background_file)) {
    
    ## match bg_mz to cluster centroid
    temp_a <- data.frame(cluster_id = clust_mz$cluster_index,
                         all_mz = all_mz)
    
    temp_b <- data.frame(clust_centroid = clust_mz$centroid, 
                         cluster_id = unique(clust_mz$cluster_index)[order(unique(clust_mz$cluster_index))])
    
    temp_c <- merge(temp_a, temp_b, by = "cluster_id")
    
    bg_centroids <- unique(temp_c[temp_c$all_mz %in% bg_mz, ])
    
    ## Remove peaks from aligned_spectra that are in bg_mz_centroid
    aligned_spectra <- aligned_spectra[, !(colnames(aligned_spectra) %in% bg_centroids$clust_centroid)]
  }
  
  filtered_mz <- as.numeric(colnames(aligned_spectra))
}
```

```{r peak alignment feature list}
if (peak_alignment_method == "featurelist") {
  
  if (is.null(feature_file)) {
    
    print("No path specified for feature list. Add path to file or choose a different peak alignment method.")
    
  }else{
    
    ## Read file with feature peaks
    feature_df <- read_xlsx(feature_file, sheet = "Sheet5-Species", skip = 1)
    feature_df <- feature_df %>% filter(`Feature (m/z)` != "Intercept")
    feature_peaks <- unlist(feature_df[,1])
    feature_peaks <- as.numeric(feature_peaks)
    
    ## Feature mz plus/minus instrument mass error, round to 3 decimal places
    mass_error <- unlist((ppm_error * feature_peaks)/1e6)
    
    feature_peaks <- data.frame(feature_mass = feature_peaks,
                                mass_error = mass_error,
                                mass_error_lower = round(feature_peaks - mass_error,3),
                                mass_error_upper = round(feature_peaks + mass_error,3))
    
    ## Reset rownames
    rownames(feature_peaks) <- NULL
    
    ## fixed objects for exporting to parallel computing
    fixed_objects <- list(mass_range = mass_range, feature_peaks = feature_peaks)
    
    feature_peak_alignment <- function(spectra_list, fixed_objects) {
      cl <- makeCluster(detectCores() - 1) # Use one less than the number of available cores
      registerDoParallel(cl)
      
      # clusterEvalQ(cl, {
      #   library(dplyr)
      #   library(sqldf)
      # })
      
      #clusterExport(cl, list("feature_peaks"))
      
      result <- foreach(i = seq_along(spectra_list), .packages = c('dplyr', 'sqldf')) %:% 
        foreach(j = seq_along(spectra_list[[i]])) %dopar% {
          
          spectrum <- spectra_list[[i]][[j]]
          feature_peaks <- fixed_objects$feature_peaks
          
          feature_matched_spectrum <- sqldf("SELECT feature_peaks.feature_mass, spectrum.*
          FROM spectrum, feature_peaks
          WHERE spectrum.mass BETWEEN feature_peaks.mass_error_lower AND feature_peaks.mass_error_upper")
      
          ## ADD SAFETY CHECK HERE
          if (nrow(feature_matched_spectrum) == 0) {
            ## if no matches, return empty result
            feature_matched_spectrum <- data.frame(feature_mass = numeric(0), intensity = numeric(0))
          } else {
            ## matches found, process normally
            feature_matched_spectrum <- subset(feature_matched_spectrum, select = -c(mass))
            feature_matched_spectrum <- aggregate(intensity ~ ., data = feature_matched_spectrum, FUN = sum)
          }
      
          feature_matched_spectrum
        }
      stopCluster(cl)
      return(result)
    }
    
    feature_matched_spectra <- feature_peak_alignment(spectra_list, fixed_objects)
    
    ## turn list of lists into dataframe
    feature_matched_spectra <- lapply(feature_matched_spectra, function(x) x %>%
                                        reduce(full_join,by = "feature_mass")) %>% reduce(full_join,by = "feature_mass")
    
    ## sort by target_mz
    feature_matched_spectra <- feature_matched_spectra[order(feature_matched_spectra$feature_mass), ]
    
    
    ## feature_mass column to rownames
    feature_matched_spectra <- feature_matched_spectra %>% 
      remove_rownames %>% 
      column_to_rownames(var = "feature_mass") %>% 
      as.data.frame()
    
    ## Add sample names as column names
    colnames(feature_matched_spectra) <- sample_names
    
    ## Replace NA with 0
    feature_matched_spectra <- replace(feature_matched_spectra, is.na(feature_matched_spectra), 0)
    
    ## Transpose so rows are samples and columns are masses
    aligned_spectra <- t(feature_matched_spectra)
    
    filtered_mz <- as.numeric(colnames(aligned_spectra))
  }
}
```

```{r normalization}
xall <- normalize_pixel(aligned_spectra, normalization_method)
```

```{r yall}
## create yall object 
yall <- foreach(i = 1:length(file_name_list), .combine = c) %do% {
  rep(i, length(file_name_list[[i]])) }

## factorize yall
yall <- factor(yall,levels=c("1","2"),labels = classes)
```

## Create data for training

## Train/Test Split

``` {r split}
sample_names_df <- read.csv("C:/Users/Jacob/OneDrive - Baylor College of Medicine/Documents/Manoj/Microbial-Project/Data/sample_names_df.csv")
sample_names_df <- sample_names_df[order(sample_names_df$X),]

## Gram stain classification
sample_names_df$gram <- ifelse(sample_names_df$class %in% c("Enterobacter cloacae complex", "Escherichia coli", "Haemophilus influenzae", "Klebsiella pneumoniae", "Pseudomonas aeruginosa"), "Gram-negative", "Gram-positive")

test_count <- round(table(sample_names_df$gram)*0.3,0)
test_index <- vector()
for (c in classes){
  test_index <- c(test_index, sample(which(sample_names_df$gram == c & is.na(sample_names_df$patient)), size = test_count[c]))
}
otr <- (1:nrow(sample_names_df))[-test_index]
sample_names_df$train_test_set <- ifelse(sample_names_df$X %in% otr, "train", "test")
```

## Below taken from Rob rc2 script for ratio calculations prior to Lasso

```{r all pairs}
## Function to compute log ratios with bounds
compute_logratios_with_bounds <- function(x, feature_names = NULL, min_valid = 10) {
  n_features <- ncol(x)
  n_samples <- nrow(x)
  n_ratios <- choose(n_features, 2)
  
  ## Initialize
  logratios <- matrix(NA_real_, nrow = n_samples, ncol = n_ratios)
  ratio_names <- character(n_ratios)
  
  ii <- 0
  for (j in 1:(n_features - 1)) {
    for (k in (j+1):n_features) {
      ii <- ii + 1
      ratio <- log(x[, j] / x[, k])
      
      ## Identify -Inf and Inf
      neg_inf_mask <- is.infinite(ratio) & ratio < 0
      pos_inf_mask <- is.infinite(ratio) & ratio > 0
      ratio[neg_inf_mask | pos_inf_mask] <- NA
      
      valid_vals <- ratio[!is.na(ratio)]
      
      ## Calculate quantiles per ratio
      if (length(valid_vals) >= min_valid) {
        q01 <- quantile(valid_vals, 0.01)
        q99 <- quantile(valid_vals, 0.99)
        
      } else {
        NA
      }
      
      ## Restore directionality of -Inf and +Inf
      ratio[neg_inf_mask] <- q01
      ratio[pos_inf_mask] <- q99
      ratio[is.na(ratio)] <- 0
      
      logratios[, ii] <- ratio
      if (!is.null(feature_names)) {
        ratio_names[ii] <- paste0(feature_names[j], "/", feature_names[k])
      } else {
        ratio_names[ii] <- paste0("V", j, "/V", k)
      }
    }
  }
  
  colnames(logratios) <- ratio_names
  return(list(logratios = logratios, ratio_names = ratio_names))
}

## Perform log ratio lasso
res <- compute_logratios_with_bounds(x = xall, feature_names = colnames(xall))
allpairs <- res$logratios
nams.p <- res$ratio_names

## Remove any features with remaining NAs
na_free_cols <- colSums(is.na(allpairs)) == 0
allpairs <- allpairs[, na_free_cols, drop = FALSE]
nams.p <- nams.p[na_free_cols]

## Keeping naming scheme the same
xtrain <- allpairs[otr,]
xtrain <- as(xtrain, "dgCMatrix")
xtest <- allpairs[-otr,]
ytrain <- yall[otr]
ytest <- yall[-otr]

model <- glmnet(
  xtrain, 
  ytrain, 
  family = "binomial", ## for logit (logarithm of the odds) or logistic regression
  standardize = FALSE, ## because intensities are already in same units
  lambda.min.ratio = 1e-05 ) ## The model will compute its own lambda sequence based on nlambda and lambda.min.ratio 

#nfolds <- nrow(xtrain)
nfolds <- 10
cvmodel <- cv.glmnet(xtrain, ytrain, nfolds = nfolds, family = "binom", type.measure = "class", standardize = F, keep = T)
```

```{r ROC Metrics}
## save index of lambda value that gives minimum cvm (mean cross-validated error)
min_lambda_index <- which(cvmodel$lambda == cvmodel$lambda.min)

## 1/(1+e^(-preval)) is the inverse of the link function?
cv_predictions <- 1/(1+exp(-cvmodel$fit.preval[,min_lambda_index]))

## build ROC for training data using minLamIdx
roc_curve <- roc(
  ytrain, 
  cv_predictions )

## create dataframe from ROC object to create plot for trade off
## of accuracy, sensitivity, and specificity
roc_df <- data.frame(
  cutoff = roc_curve$thresholds, 
  sensitivity = roc_curve$sensitivities, 
  specificity = roc_curve$specificities )

roc_df$accuracy <- (roc_df$sensitivity*length(roc_curve$cases) + 
                      roc_df$specificity*length(roc_curve$controls)) / (length(roc_curve$cases) + 
                                                                          length(roc_curve$controls) )

## plot trade off of accuracy, sensitivity, and specificity
roc_metrics <- ggplot(roc_df) + geom_line(aes(cutoff, sensitivity, col = "Sensitivity")) + 
  geom_line(aes(cutoff, specificity, col = "Specificity")) + 
  geom_line(aes(cutoff, accuracy, col = "Accuracy")) +
  labs(x = "cutoff", y = "%", color="") +
  ggtitle("Trade off of performance metrics for determining threshold cutoff value")
```

```{r Threshold Coordinates}
## Identify Threshold Coordinates where Accuracy, Sensitivity, and Specificity Cross
## Set threshold for labeling classes --> balance of true positive and false positive rates.
best_threshold <- as.double(coords(roc_curve, 
                                   "best", ## coordinates for best threshold value
                                   ret = "threshold", ## coordinates to return
                                   best.method = "youden" )[1,1]) ## optimal cut-off is the threshold that maximizes the distance to the identity (diagonal) line
```

```{r CV Confusion Matrix}
## predict classes based on threshold
cv_p_thresh <- ifelse(cv_predictions < best_threshold, classes[1], classes[2])

cv_p_class <- factor(cv_p_thresh, levels(ytrain))

## simple confusion matrix table
cv_cm <- table(True=ytrain,
               Predict=cv_p_class)
```

```{r Training Histogram}
train_df <- data.frame(file_name=sample_names[otr], 
                       true_class=ytrain, 
                       prediction_class=cv_p_class, 
                       probability=cv_predictions)

rownames(train_df) <- NULL

train_wrong_preds <- train_df %>%
  filter(true_class != prediction_class)
```

```{r Report Model Coefficients}
lasso_coef <- reportCoef(allpairs, model, cvmodel$lambda.min, nams.p, classes)
```

```{r Testing}
test_p <- predict(model,
                  xtest,
                  s = cvmodel$lambda.min, ## Value of the penalty parameter lambda 
                  ## at which predictions are required
                  type = "response" ) ## to get prediction values rather than linker function values
```

```{r Testing Confusion Matrix}
test_p_thresh <- ifelse(test_p < best_threshold, classes[1], classes[2]) 
test_p_class <- factor(test_p_thresh, levels(ytest))

## simple confusion matrix table
test_cm <- table(True=ytest,
                 Predict=test_p_class)
```

```{r Test Histogram}
test_df <- data.frame(file_name=sample_names[-c(otr)], 
                      true_class=ytest, 
                      prediction_class=test_p_class, 
                      probability=as.numeric(test_p))

rownames(test_df) <- NULL

test_wrong_preds <- test_df %>%
  filter(true_class != prediction_class)
```

```{r save model, include=FALSE}
save(model, cvmodel, filtered_mz, best_threshold,mass_range, ppm_error, normalization_method, seed, classes, lasso_coef, peak_alignment_method,
     file=file.path(files_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_",proj_name, "_model.RData")))
```

```{r}
save(list = ls(), file=file.path(files_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_",proj_name, "_ALL.RData")))
```

```{r save files, include = FALSE}
## training set files

write.csv(cv_cm, 
          file = file.path(files_dir, "train_cm.csv"))

write.csv(train_df, 
          row.names = FALSE,
          file.path(files_dir, "train_preds.csv"))

write.csv(train_wrong_preds, 
          row.names = FALSE,
          file.path(files_dir, "misclassified_train_preds.csv"))

write.csv(as.matrix(lasso_coef), 
          file.path(files_dir, "lasso_coefficients.csv"))

## test set files

write.csv(test_cm, 
          file = file.path(files_dir, "test_cm.csv"))

write.csv(test_df, 
          row.names = FALSE,
          file.path(files_dir, "test_preds.csv"))

write.csv(test_wrong_preds, 
          row.names = FALSE,
          file.path(files_dir, "misclassified_test_preds.csv"))
```

```{r save plots, include=FALSE}
png(filename=file.path(files_dir, "cv_plot.png"))
plot(cvmodel)
title("cross-validation curve : binomial family", line = 2.5)
dev.off()

png(filename=file.path(files_dir, "roc_plot.png"))
plot(roc_curve, 
     print.thres="best", 
     print.thres.best.method="youden",
     print.auc=TRUE, 
     auc.polygon=TRUE,
     main = "ROC Curve")
dev.off()

ggsave(roc_metrics, filename = file.path(files_dir, "roc_metrics_thresh.png"))
```

<br>

#### **Preprocessing and Statistical Model Settings**

```{r chunk3, fig.align = "center"}
if (peak_alignment_method == "clustering") {
  cluster_bin_size <- c("Cluster Height:", clust_h)
} else if (peak_alignment_method == "binning") {
  cluster_bin_size <- c("Bin Size:", "0.01")
} else if (peak_alignment_method == "featurelist") {
  cluster_bin_size <- c("Peak Mass Error:", paste0(ppm_error, " ppm"))
}

if (is.null(background_file)) {
  bg_exclusion <- "no"
} else if (!is.null(background_file)) {
  bg_exclusion <- "yes"
}

settings_df <- rbind(c("Mass Range:", paste0('<i>m/z</i> ', mass_range[1], " - ", mass_range[2])),
                     c("Peak Alignment Method:", peak_alignment_method),
                     cluster_bin_size,
                     c("Background Peak Exclusion:", bg_exclusion),
                     c("Normalization Method:", normalization_method),
                     c("Train/Test Split:", paste0((train_fraction*100),"/",(100-(train_fraction*100)))),
                     c("Randomization Seed:", seed))

classes2 <- tools::toTitleCase(gsub("_", " ", classes))

kable(settings_df,
      #caption = "Preprocessing and LASSO Settings",
      row.names = FALSE,
      align = "l",
      format = "html",
      escape = FALSE)%>%
  column_spec(1:2, width = "3in")%>% 
  kable_styling(full_width = FALSE, 
                font_size = 14)

cols <- rev(c(hue_pal()(2)))
```

```{r chunk4}
cv_cm <- as.data.frame.matrix(cv_cm)
test_cm <- as.data.frame.matrix(test_cm)

cv_cm <- cbind(c("True", "True"),
               classes2,
               cv_cm)

test_cm <- cbind(c("True", "True"),
                 classes2,
                 test_cm)

rownames(cv_cm) <- NULL
rownames(test_cm) <- NULL

colnames(cv_cm) <- c(".", "  ", classes2)
colnames(test_cm) <- c(".", "  ", classes2)

names(cv_cm)[1] <- cell_spec(names(cv_cm)[1], color = "white")
names(test_cm)[1] <- cell_spec(names(test_cm)[1], color = "white")

cv_accuracy <- rbind(c(paste0(classes2[1], " Recall: "), 
                       paste0(format(round((cv_cm[1,3]/rowSums(cv_cm[,3:4])[1])*100, 1), nsmall = 1), "%")),
                     c(paste0(classes2[2], " Recall: "), 
                       paste0(format(round((cv_cm[2,4]/rowSums(cv_cm[,3:4])[2])*100,1), nsmall = 1), "%")),
                     c("Overall Accuracy: ", 
                       paste0(format(round(((cv_cm[1,3] + cv_cm[2,4])/sum(cv_cm[, 3:4]))*100, 1), nsmall = 1), "%")))

test_accuracy <- rbind(c(paste0(classes2[1], " Recall: "), 
                         paste0(format(round((test_cm[1,3]/rowSums(test_cm[,3:4])[1])*100, 1), nsmall = 1), "%")),
                       c(paste0(classes2[2], " Recall: "), 
                         paste0(format(round((test_cm[2,4]/rowSums(test_cm[,3:4])[2])*100,1), nsmall = 1), "%")),
                       c("Overall Accuracy: ", 
                         paste0(format(round(((test_cm[1,3] + test_cm[2,4])/sum(test_cm[, 3:4]))*100, 1), nsmall = 1), "%")))
```

<br>

#### **Training Set Confusion Matrix**

```{r chunk6, fig.align = "center"}
kable(cv_cm,
      #caption = "Training Set",
      align = "c",
      format = "html",
      escape = FALSE) %>%
  kable_styling(full_width = FALSE) %>%
  add_header_above(c("", " ", "Predict" = 2)) %>%
  column_spec(1, bold = TRUE) %>%
  column_spec(2, bold = TRUE) %>%
  collapse_rows(columns = 1) %>% 
  column_spec(3, background = "#c3fcb5")

kable(cv_accuracy,
      row.names = FALSE,
      align = "r") %>% 
  column_spec(1, bold = TRUE) %>%
  kable_minimal(full_width = FALSE,
                bootstrap_options = "condensed",
                html_font = "Calibri",
                font_size = 16)
```

<br>

#### **Test Set Confusion Matrix**

```{r chunk7, fig.align = "center"}
kable(test_cm,
      #caption = "Test Set", 
      align = "c",
      format = "html",
      escape = FALSE) %>%
  kable_styling(full_width = FALSE) %>%
  add_header_above(c("", " ", "Predict" = 2)) %>%
  column_spec(1, bold = TRUE) %>%
  column_spec(2, bold = TRUE) %>%
  collapse_rows(columns = 1) %>%
  column_spec(3, background = "#c3fcb5")

kable(test_accuracy,
      row.names = FALSE,
      align = "r") %>% 
  column_spec(1, bold = TRUE) %>%
  kable_minimal(full_width = FALSE,
                bootstrap_options = "condensed",
                html_font = "Calibri",
                font_size = 16)
```

<br>

```{r roc curve report, fig.align='center', fig.width=4, fig.height=4}
plot(roc_curve, 
     print.thres="best", 
     print.thres.best.method="youden",
     print.auc=TRUE, 
     auc.polygon=TRUE,
     main = "ROC")
```

<br>

#### **LASSO Model Predictive Feature Weights**

```{r chunk5}
if(normalization_method == "median"){
  lasso_coef2 <- data.frame(cbind(c("Intercept",
                                    format(rownames(lasso_coef[2:nrow(lasso_coef),]), nsmall = 3)),
                                  as.numeric(lasso_coef[, 1])))
}else {
  lasso_coef2 <- data.frame(cbind(c("Intercept", 
                                    format(rownames(lasso_coef[2:nrow(lasso_coef),]), nsmall = 3)), 
                                  format(round(as.numeric(lasso_coef[, 1]),3), nsmall = 3)))
}

colnames(lasso_coef2) <- c("Features", paste0("Weights (", classes2[2], ")"))
```

```{r}
## remove intercept row
intercept <- lasso_coef2[1, 2]

## split features into positive and negative
pos_features <- lasso_coef2[which(as.numeric(lasso_coef2[[2]]) > 0), ]
neg_features <- lasso_coef2[which(as.numeric(lasso_coef2[[2]]) < 0), ]

pos_features <- subset(pos_features, Features != "Intercept")
neg_features <- subset(neg_features, Features != "Intercept")

max_len <- max(nrow(pos_features), nrow(neg_features))

pos_features <- pos_features[c(NA, seq_len(nrow(pos_features)), rep(NA, max_len - nrow(pos_features))), ]
neg_features <- neg_features[c(NA, seq_len(nrow(neg_features)), rep(NA, max_len - nrow(neg_features))), ]
empty_col <- c(intercept, rep(NA, max_len))

split_lasso_coefs <- cbind(pos_features, empty_col, neg_features)

split_lasso_coefs[is.na(split_lasso_coefs)] <- ""

colnames(split_lasso_coefs) <- c(paste0(classes2[2], " Features"), 
                                 paste0(classes2[2], " Weights"), 
                                 "Intercept", 
                                 paste0(classes2[1], " Features"), 
                                 paste0(classes2[1], " Weights"))
```

```{r, fig.align = "center", eval = FALSE, include = FALSE}
lasso_coef2 %>%
  kable(
    #caption = "LASSO Model Predictive Feature Weights",
    row.names = FALSE,
    align = "c") %>% 
  kable_styling(full_width = FALSE, 
                font_size = 14) %>%
  column_spec(1:2,width = "2in")
```

```{r, fig.align = "center"}
split_lasso_coefs %>%
  kable(
    #caption = "LASSO Model Predictive Feature Weights",
    row.names = FALSE,
    align = "c") %>% 
  kable_styling(full_width = FALSE, 
                font_size = 14) %>%
  column_spec(1:5,width = "2in")
```

```{r chunk9, fig.width=8, fig.height=3, fig.align = "center"}
train_plot <- ggplot(train_df, aes(x=probability, fill=true_class, color=true_class)) + 
  geom_histogram(binwidth=0.01, alpha=0.25, position="identity",boundary=0) + 
  ggtitle("Prediction Probabilities: Training Set") +
  geom_vline(xintercept = best_threshold, linewidth = 0.75,  color = "black", linetype = "dashed") +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1), minor_breaks = seq(0, 1, by = 0.05), expand = c(0.05,0)) +
  #scale_y_continuous(breaks = seq(0, nrow(train_df), by = 5), minor_breaks = seq(0, nrow(train_df), by = 1), expand = c(0.01,0)) +
  scale_color_manual(values = rev(cols), labels = c(classes2[1], classes2[2])) +
  scale_fill_manual(values = rev(cols), labels = c(classes2[1], classes2[2])) +
  labs(x = "Prediction Probability", y = "Spectra Count", color="True Class", fill = "True Class") +
  #theme_minimal(base_size = 9)
  theme_minimal() +
  theme(legend.position = "bottom")

test_plot <- ggplot(test_df, aes(x=probability, fill=true_class, color=true_class)) + 
  geom_histogram(binwidth=0.01, alpha=0.25, position="identity",boundary=0) + 
  ggtitle("Prediction Probabilities: Test Set") +
  geom_vline(xintercept = best_threshold, linewidth = 0.75,  color = "black", linetype = "dashed") +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1), minor_breaks = seq(0, 1, by = 0.05), expand = c(0.05,0)) +
  #scale_y_continuous(breaks = seq(0, nrow(test_df), by = 5), minor_breaks = seq(0, nrow(test_df), by = 1), expand = c(0.01,0)) +
  scale_color_manual(values = rev(cols), labels = c(classes2[1], classes2[2])) +
  scale_fill_manual(values = rev(cols), labels = c(classes2[1], classes2[2])) +
  labs(x = "Prediction Probability", y = "Spectra Count", color="True Class", fill = "True Class") +
  #theme_minimal(base_size = 9)
  theme_minimal() +
  theme(legend.position = "bottom")

#ggarrange(train_plot, test_plot, common.legend = TRUE,legend = "bottom")
```

```{r}
ggsave(plot=train_plot, filename = file.path(files_dir, "train_histogram.png"), bg = "white")
ggsave(plot=test_plot, filename = file.path(files_dir, "test_histogram.png"), bg = "white")
```

```{r chunk10}
## Add misclassified training samples
train_wrong_preds <- train_df %>%
  filter(true_class != prediction_class)

train_wrong_preds <- train_wrong_preds[order(train_wrong_preds$true_class), ]

train_wrong_preds$true_class <- gsub(classes[1], classes2[1], gsub(classes[2], classes2[2],train_wrong_preds$true_class))
train_wrong_preds$prediction_class <- gsub(classes[1], classes2[1], gsub(classes[2], classes2[2],train_wrong_preds$prediction_class))

train_wrong_preds$probability <- round(train_wrong_preds$probability, 3)

## Add misclassified test samples
test_wrong_preds <- test_df %>%
  filter(true_class != prediction_class)

test_wrong_preds <- test_wrong_preds[order(test_wrong_preds$true_class), ]

test_wrong_preds$true_class <- gsub(classes[1], classes2[1], gsub(classes[2], classes2[2],test_wrong_preds$true_class))
test_wrong_preds$prediction_class <- gsub(classes[1], classes2[1], gsub(classes[2], classes2[2],test_wrong_preds$prediction_class))

test_wrong_preds$probability <- round(test_wrong_preds$probability, 3)
```

<br>

#### **Training Set Misclassifications**

```{r chunk11, fig.align = "center"}
train_plot

kable(train_wrong_preds,
      #caption = "Training Set Misclassifications",
      col.names = c("Sample Name", "True Class", "Predicted Class", "Probability"),
      row.names = FALSE,
      align = "l")  %>%
  kable_styling(position = "center", 
                bootstrap_options = c("striped", "condensed"),
                full_width = FALSE, 
                font_size = 14)
```

<br>

#### **Test Set Misclassifications**

```{r chunk12, fig.align = "center"}
test_plot

kable(test_wrong_preds,
      #caption = "Test Set Misclassifications",
      col.names = c("Sample Name", "True Class", "Predicted Class", "Probability"),
      row.names = FALSE,
      align = "l")  %>%
  kable_styling(position = "center", 
                bootstrap_options = c("striped", "condensed"),
                full_width = FALSE, 
                font_size = 14)
```

<br>

#### **Train/Test Data Split**

```{r chunk13}
## Add list of samples for training and testing
train_samples <- sort(train_df$file_name)
test_samples <- sort(test_df$file_name)

n <- max(length(train_samples), length(test_samples))
length(train_samples) <- n                      
length(test_samples) <- n

samples <- cbind("Training Samples" = train_samples,
                 "Test Samples" = test_samples)

samples[is.na(samples)] <- ""
```

```{r chunk14}
kable(samples,
      #caption = "Train/Test Data Split",
      row.names = FALSE,
      align = "l") %>%
  kable_minimal(full_width = FALSE,
                bootstrap_options = "condensed",
                html_font = "Calibri",
                font_size = 12)
```